balancers:
  ingress:
    annotations:
      - nginx.ingress.kubernetes.io/ssl-redirect=true
      - nginx.ingress.kubernetes.io/use-forwarded-headers=true
      - nginx.ingress.kubernetes.io/enable-real-ip=true
    service: web
    ports:
      80: 3000
      443: 3000

resources:
  database:
    type: postgres

services:
  worker:
    agent: true
    build: .
    command: bundle exec good_job start
    resources:
      - database
  web:
    build: .
    sticky: true
    domain: chuspace.com
    ports:
      - 3000
    resources:
      - database
    tls:
      redirect: true
