balancers:
  ingress:
    annotations:
      - kubernetes.io/ingress-class=alb
      - nginx.ingress.kubernetes.io/ssl-redirect="true"
    service: web
    ports:
      80: 3000
      443: 3000

resources:
  database:
    type: postgres

services:
  worker:
    build: .
    command: bundle exec good_job start
    resources:
      - database
  web:
    build: .
    ports:
      - 3000
    resources:
      - database
