resources:
  database:
    type: postgres
  memcache:
    type: memcached

services:
  worker:
    build: .
    command: bundle exec good_job start
    resources:
      - database
      - memcache
  web:
    build: .
    domain: chuspace.com
    sticky: true
    tls:
      redirect: true
    termination:
      grace: 60
    scale:
      count: 3
      cpu: 256
      memory: 512
    health:
      grace: 10
      interval: 30
      path: /heartbeat
      timeout: 3
    port: 3000
    resources:
      - database
      - memcache
