resources:
  database:
    type: postgres

services:
  worker:
    build: .
    scale:
      count: 2
      cpu: 256
      memory: 512
    command: bundle exec sidekiq -C config/sidekiq.yml
    resources:
      - database
  web:
    build: .
    domain: chuspace.com
    sticky: true
    tls:
      redirect: true
    termination:
      grace: 60
    scale:
      count: 2
      cpu: 256
      memory: 1024
    health:
      grace: 10
      interval: 30
      path: /heartbeat
      timeout: 3
    port: 3000
    resources:
      - database
  timers:
    session:
      command: bin/rails db:sessions:trim
      schedule: '0 1 * * *'
      service: worker
