resources:
  database:
    type: mysql
  database-replica:
    type: mysql
  memcached:
    type: memcached

services:
  worker:
    build: .
    scale:
      count: 2
      cpu: 256
      memory: 512
    command: bundle exec aws_sqs_active_job --queue default
    resources:
      - database
      - database-replica
  web:
    annotations:
      - nginx.ingress.kubernetes.io/use-forwarded-headers=true
      - nginx.ingress.kubernetes.io/use-proxy-protocol=true
      - nginx.ingress.kubernetes.io/backend-protocol=http
      - nginx.ingress.kubernetes.io/proxy-add-original-uri-header=true
      - nginx.ingress.kubernetes.io/server-tokens=chuspace
    build: .
    domain: chuspace.com
    termination:
      grace: 60
    scale:
      count: 4
      cpu: 256
      memory: 1024
    health:
      grace: 10
      interval: 30
      path: /heartbeat
      timeout: 3
    port: 3000
    resources:
      - database
      - database-replica
      - memcached
