balancers:
  other:
    service: web
    ports:
      443: 3000

resources:
  database:
    type: postgres

services:
  worker:
    build: .
    command: bundle exec good_job start
    scale:
      count: 1-3
      targets:
        cpu: 70
        memory: 90
    resources:
      - database
  web:
    build: .
    port: https:3000
    scale:
      count: 1-3
      targets:
        cpu: 70
        memory: 90
    resources:
      - database
