resources:
  database:
    type: postgres

services:
  worker:
    agent: true
    build: .
    command: bundle exec good_job start
    resources:
      - database
  web:
    build: .
    sticky: true
    domain: chuspace.com
    port: 3000
    resources:
      - database
