balancers:
  ingress:
    annotations:
      - kubernetes.io/ingress.class=alb
      - alb.ingress.kubernetes.io/scheme=internet-facing
      - service.beta.kubernetes.io/aws-load-balancer-type=
      - nginx.ingress.kubernetes.io/use-forwarded-headers=true
      - nginx.ingress.kubernetes.io/enable-real-ip=true
      - nginx.ingress.kubernetes.io/compute-full-forwarded-for=true
      - nginx.ingress.kubernetes.io/use-proxy-protocol=true
      - nginx.ingress.kubernetes.io/server-tokens=chuspace
      - nginx.ingress.kubernetes.io/ssl-redirect=true
      - nginx.ingress.kubernetes.io/force-ssl-redirect=true
    service: web
    class: alb
    ports:
      80: 3000
      443: 3000

resources:
  database:
    type: postgres

services:
  worker:
    agent: true
    build: .
    command: bundle exec good_job start
    resources:
      - database
  web:
    build: .
    sticky: true
    domain: chuspace.com
    port: 3000
    ports:
      - 3000
    tls:
      redirect: true
    resources:
      - database
