resources:
  database:
    type: mysql
  database-replica:
    type: mysql
  redis:
    type: redis

services:
  worker:
    build: .
    scale:
      count: 2
      cpu: 256
      memory: 512
    command: bundle exec sidekiq -C config/sidekiq.yml
    resources:
      - database
      - database-replica
      - redis
  web:
    annotations:
      - nginx.ingress.kubernetes.io/use-forwarded-headers=true
    build: .
    domain: chuspace.com
    termination:
      grace: 60
    scale:
      count: 2
      cpu: 256
      memory: 512
    health:
      grace: 10
      interval: 30
      path: /heartbeat
      timeout: 3
    port: 3000
    resources:
      - database
      - database-replica
      - redis
  timers:
    session:
      command: bin/rails db:sessions:trim
      schedule: '0 1 * * *'
      service: worker
