balancers:
  other:
    annotations:
      - service.beta.kubernetes.io/aws-load-balancer-type=alb
    service: web
    ports:
      80: 3000
      443: 3000

resources:
  database:
    type: postgres

services:
  worker:
    build: .
    command: bundle exec good_job start
    resources:
      - database
  web:
    build: .
    ports:
      - 3000
    resources:
      - database
