balancers:
  ingress:
    annotations:
      - nginx.ingress.kubernetes.io/use-forwarded-headers=true
      - nginx.ingress.kubernetes.io/enable-real-ip=true
      - nginx.ingress.kubernetes.io/compute-full-forwarded-for=true
      - nginx.ingress.kubernetes.io/use-proxy-protocol=true
      - nginx.ingress.kubernetes.io/server-tokens=chuspace
      - nginx.ingress.kubernetes.io/configuration-snippet="if ($http_x_forwarded_proto = 'http') { return 301 https://$host$request_uri; }"
    service: web
    ports:
      80: 3000
      443: 3000

resources:
  database:
    type: postgres

services:
  worker:
    agent: true
    build: .
    command: bundle exec good_job start
    resources:
      - database
  web:
    build: .
    sticky: true
    domain: chuspace.com
    ports:
      - 3000
    resources:
      - database
