resources:
  database:
    type: postgres

services:
  worker:
    agent: true
    build: .
    command: bundle exec good_job start
    resources:
      - database
  web:
    build: .
    domain: chuspace.com
    sticky: true
    tls:
      redirect: true
    termination:
      grace: 60
    health:
      grace: 10
      interval: 30
      path: /heartbeat
      timeout: 3
    port: 3000
    resources:
      - database
