version: "3"
services:
  web:
    image: chuspace2/app:main
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/usr/src/app
      - bundle:/app/.bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
  worker:
    image: chuspace2/app:main
    command: bundle exec aws_sqs_active_job --queue default
    volumes:
      - .:/usr/src/app
      - bundle:/app/.bundle
volumes:
  bundle:
