version: "3"
services:
  web:
    image: chuspace2/app:main
    command: bundle exec rails s -p 3000
    volumes:
      - .:/app
      - bundle:/app/.bundle
    ports:
      - "3000:3000"
  worker:
    image: chuspace2/app:main
    command: bundle exec aws_sqs_active_job --queue default
    volumes:
      - .:/app
      - bundle:/app/.bundle
volumes:
  bundle:
