development:
  adapter: redis
  url: <%= Rails.application.credentials.redis[:websocket] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis[:websocket] %>
  channel_prefix: chuspace_production
