default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  connect_timeout: 5
  read_timeout: 5
  write_timeout: 5
  variables:
    max_execution_time: 15000 # ms
    lock_wait_timeout: 10
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'mysql2://localhost:3306/chuspace_development') %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'mysql2://localhost:3306/chuspace_test') %>

production:
  primary:
    <<: *default
    ssl_mode: verify_identity
    sslca: <%= ENV.fetch('SSL_CA_PATH', '/etc/ssl/cert.pem') %>
    url: <%= ENV.fetch('DATABASE_URL', 'mysql2://localhost:3306/chuspace') %>
  primary_replica:
    <<: *default
    ssl_mode: verify_identity
    sslca: <%= ENV.fetch('SSL_CA_PATH', '/etc/ssl/cert.pem') %>
    url: <%= ENV.fetch('DATABASE_REPLICA_URL', 'mysql2://localhost:3306/chuspace') %>
    replica: true
    database_tasks: false
