default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: chuspace_development
  primary_replica:
    <<: *default
    database: chuspace_development_replica

test:
  primary:
    <<: *default
    database: chuspace_test
  primary_replica:
    <<: *default
    database: chuspace_test_replica

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_REPLICA_URL'] %>
    replica: true
