default: &default
  adapter: postgresql
  encoding: unicode
  connect_timeout: 5
  variables:
    statement_timeout: 15s
    lock_timeout: 10s
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chuspace_development

test:
  <<: *default
  database: chuspace_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
