version: "3"
services:
  web:
    image: chuspace2/app:main
    command: bundle exec rails s -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
  worker:
    image: chuspace2/app:main
    command: bundle exec aws_sqs_active_job --queue default
    volumes:
      - .:/app
    env_file:
      - .env
