production: &production
  url: <%= Rails.application.credentials.redis[:websocket] %>
  timeout: 1

development: &development
  url: <%= Rails.application.credentials.redis[:websocket] %>
  timeout: 1

test:
  <<: *development
