production: &production
  url: <%= ENV.fetch('REDIS_URL') %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  timeout: 1

development: &development
  url: <%= ENV.fetch('REDIS_URL') %>
  timeout: 1

test:
  <<: *development
